---
apiVersion: v1
kind: Namespace
metadata:
  name: ipam
---
apiVersion: v1
kind: Secret
metadata:
  name: ipam-db-secret
  namespace: ipam
type: Opaque
stringData:
  MARIADB_ROOT_PASSWORD: "SuperSecureRootPass!"
  MARIADB_USER: "phpipam"
  MARIADB_PASSWORD: "SuperSecureAppPass!"
  MARIADB_DATABASE: "phpipam"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-data
  namespace: ipam
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  namespace: ipam
spec:
  serviceName: mariadb
  replicas: 1
  selector:
    matchLabels: { app: mariadb }
  template:
    metadata:
      labels: { app: mariadb }
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.11
          imagePullPolicy: IfNotPresent
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom: { secretKeyRef: { name: ipam-db-secret, key: MARIADB_ROOT_PASSWORD } }
            - name: MARIADB_USER
              valueFrom: { secretKeyRef: { name: ipam-db-secret, key: MARIADB_USER } }
            - name: MARIADB_PASSWORD
              valueFrom: { secretKeyRef: { name: ipam-db-secret, key: MARIADB_PASSWORD } }
            - name: MARIADB_DATABASE
              valueFrom: { secretKeyRef: { name: ipam-db-secret, key: MARIADB_DATABASE } }
          ports:
            - name: mysql
              containerPort: 3306
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mariadb-data
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: ipam
spec:
  selector: { app: mariadb }
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpipam
  namespace: ipam
spec:
  replicas: 1
  selector:
    matchLabels: { app: phpipam }
  template:
    metadata:
      labels: { app: phpipam }
    spec:
      containers:
        - name: web
          image: phpipam/phpipam-www:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: "Pacific/Auckland"
            - name: IPAM_DATABASE_HOST
              value: "mariadb.ipam.svc.cluster.local"
            - name: IPAM_DATABASE_NAME
              valueFrom: { secretKeyRef: { name: ipam-db-secret, key: MARIADB_DATABASE } }
            - name: IPAM_DATABASE_USER
              valueFrom: { secretKeyRef: { name: ipam-db-secret, key: MARIADB_USER } }
            - name: IPAM_DATABASE_PASS
              valueFrom: { secretKeyRef: { name: ipam-db-secret, key: MARIADB_PASSWORD } }
            - name: IPAM_AUTO_MIGRATE
              value: "true"
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet: { path: /, port: http }
            initialDelaySeconds: 20
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /, port: http }
            initialDelaySeconds: 60
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: phpipam
  namespace: ipam
spec:
  selector: { app: phpipam }
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: phpipam-cron
  namespace: ipam
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: cron
              image: phpipam/phpipam-cron:latest
              imagePullPolicy: IfNotPresent
              env:
                - name: TZ
                  value: "Pacific/Auckland"
                - name: IPAM_DATABASE_HOST
                  value: "mariadb.ipam.svc.cluster.local"
                - name: IPAM_DATABASE_NAME
                  valueFrom: { secretKeyRef: { name: ipam-db-secret, key: MARIADB_DATABASE } }
                - name: IPAM_DATABASE_USER
                  valueFrom: { secretKeyRef: { name: ipam-db-secret, key: MARIADB_USER } }
                - name: IPAM_DATABASE_PASS
                  valueFrom: { secretKeyRef: { name: ipam-db-secret, key: MARIADB_PASSWORD } }
