---
- name: Deploy IPAM to Kubernetes
  hosts: localhost
  connection: local
  gather_facts: false
  
  tasks:
    - name: Deploy IPAM application
      kubernetes.core.k8s:
        state: present
        src: deploy.yml

    - name: Show access info
      debug:
        msg: "Access phpIPAM at http://<NODE_IP>:30080"