---
- name: Deploy IPAM to Kubernetes
  hosts: localhost
  connection: local
  gather_facts: false
  
  tasks:
    - name: Deploy IPAM application using kubectl
      shell: kubectl apply -f deploy.yml
      register: kubectl_result

    - name: Show deployment result
      debug:
        msg: "{{ kubectl_result.stdout }}"

    - name: Show access info
      debug:
        msg: "Access phpIPAM at http://<NODE_IP>:30080"